export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6IkNhdWEiLCJlbWFpbCI6ImNhdWFAZ21haWwuY29tIiwiaWF0IjoxNjk3MjIzNzI4LCJleHAiOjE2OTc4Mjg1MjgsImF1ZCI6InVzZXJzIiwiaXNzIjoibG9naW4iLCJzdWIiOiIyIn0.HavIKEFvqlI6g4divgb-IXUmL5XVH5tMZafTlJzwUTw';
